import requests

def weather(api_key, city):
    # this is the url which gonna hit ....and takes city and api_key as arguments.
    res = requests.get(f'https://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric')
    json_data = res.json()

    if json_data['cod'] == 200:
        # status code 200 is a succes code ..it present at last of json data
        print(f"Weather in {city}")
        print(f"Temperature: {json_data['main']['temp']}°C")
        print(f"Description: {json_data['weather'][0]['description']}")
        print(f"Humidity: {json_data['main']['humidity']}%")
        print(f"Pressure: {json_data['main']['pressure']} ")
        print(f"Wind Speed: {json_data['wind']['speed']} m/s")
        print(f"Visibility: {json_data['visibility']} m")

    else:
        print("Weather Not Present... Try Again with another Location.")

if __name__ == "__main__":
    # this  is the api_key generated by signing in on OPENWEATHERMAP website .
    api_key = '33c03cf6b9ece957ed4b23b092773269' 
    city = input("Enter the city name: ")
    weather(api_key, city)